export const ERRORS = {

    INVALID_CATEGORY_ID: "Invalid category ID",
    INVALID_COURSE_ID: "Invalid course ID",
    INVALID_TOPIC_ID: "Invalid topic ID",
    INVALID_SUB_TOPIC_ID: "Invalid sub-topic ID",
    INVALID_TITLE: "Invalid title",
    INVALID_DESCRIPTION: "Invalid description",
    INVALID_IMAGE: "Invalid image",
    INVALID_PRICE: "Invalid price",
    INVALID_DURATION: "Invalid duration",
    INVALID_ACTIVE: "Invalid active status",
    INVALID_VIEW_INDEX: "Invalid view index",
    UNABLE_TO_FETCH_CATEGORIES: "Unable to fetch categories",
    UNABLE_TO_FETCH_CATEGORY: "Unable to fetch category",
    UNABLE_TO_FETCH_CATEGORIES_AND_COURSES: "Unable to find categories and their courses",
    UNABLE_TO_CREATE_CATEGORY: "Unable to create category",
    UNABLE_TO_UPDATE_CATEGORY: "Unable to update category",
    UNABLE_TO_DELETE_CATEGORY: "Unable to delete category",
    UNABLE_TO_FETCH_COURSES: "Unable to fetch courses",
    UNABLE_TO_FETCH_COURSE: "Unable to fetch course",
    UNABLE_TO_CREATE_COURSE: "Unable to create course",
    UNABLE_TO_UPDATE_COURSE: "Unable to update course",
    UNABLE_TO_DELETE_COURSE: "Unable to delete course",
    COURSE_NOT_FOUND: "Course not found",
    CATEGORY_NOT_FOUND: "Category not found",
    UNABLE_TO_FETCH_TOPICS: "Unable to fetch topics",
    UNABLE_TO_FETCH_TOPIC: "Unable to fetch topic",
    UNABLE_TO_CREATE_TOPIC: "Unable to create topic",
    UNABLE_TO_UPDATE_TOPIC: "Unable to update topic",
    UNABLE_TO_DELETE_TOPIC: "Unable to delete topic",
    TOPIC_NOT_FOUND: "Topic not found",
    UNABLE_TO_FETCH_SUB_TOPICS: "Unable to fetch sub-topics",
    UNABLE_TO_FETCH_SUB_TOPIC: "Unable to fetch sub-topic",
    UNABLE_TO_CREATE_SUB_TOPIC: "Unable to create sub-topic",
    UNABLE_TO_UPDATE_SUB_TOPIC: "Unable to update sub-topic",
    UNABLE_TO_DELETE_SUB_TOPIC: "Unable to delete sub-topic",
    SUB_TOPIC_NOT_FOUND: "Sub-topic not found",
    INVALID_USER_ID: "Invalid user ID",
    INVALID_EMAIL: "Invalid email",
    INVALID_FULL_NAME: "Invalid full name",
    INVALID_PHONE: "Invalid phone",
    INVALID_COMPANY: "Invalid company",
    INVALID_ADDRESS: "Invalid address",
    UNABLE_TO_ADD_USER_BY_EMAIL: "Unable to add or resolve user by email",
    USER_NOT_FOUND: "User not found",
    USER_EMAIL_ALREADY_EXISTS: "A user with this email already exists",
    UNABLE_TO_FETCH_USERS: "Unable to fetch users",
    UNABLE_TO_FETCH_USER: "Unable to fetch user",
    UNABLE_TO_CREATE_USER: "Unable to create user",
    UNABLE_TO_UPDATE_USER: "Unable to update user",
    UNABLE_TO_DELETE_USER: "Unable to delete user",
    UNABLE_TO_FETCH_TESTIMONIALS: "Unable to fetch testimonials",
    UNABLE_TO_FETCH_TESTIMONIAL: "Unable to fetch testimonial",
    UNABLE_TO_CREATE_TESTIMONIAL: "Unable to create testimonial",
    UNABLE_TO_UPDATE_TESTIMONIAL: "Unable to update testimonial",
    UNABLE_TO_DELETE_TESTIMONIAL: "Unable to delete testimonial",
    TESTIMONIAL_NOT_FOUND: "Testimonial not found",
    INVALID_TESTIMONIAL: "Invalid testimonial",
    INVALID_RATINGS: "Invalid ratings",
    INVALID_TESTIMONIAL_ID: "Invalid testimonial ID",
    INVALID_TESTIMONIAL_COURSE_ID: "Invalid testimonial course ID",
    INVALID_TESTIMONIAL_USER_ID: "Invalid testimonial user ID",
}

export const SWAGGER = {
    CATEGORIES: "Categories",
    COURSES: "Courses",
    TOPICS: "Topics",
    SUB_TOPICS: "Sub-Topics",
    USERS: "Users",
    TESTIMONIALS: "Testimonials",
}